apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: C:\Users\Paulo_Bumba\AppData\Local\Microsoft\WinGet\Links\kompose.exe convert -f docker-compose.yml
    kompose.version: 1.37.0 (fb0539e64)
  labels:
    io.kompose.service: notification-service
  name: notification-service
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: notification-service
  template:
    metadata:
      annotations:
        kompose.cmd: C:\Users\Paulo_Bumba\AppData\Local\Microsoft\WinGet\Links\kompose.exe convert -f docker-compose.yml
        kompose.version: 1.37.0 (fb0539e64)
      labels:
        io.kompose.service: notification-service
    spec:
      containers:
        - env:
            - name: ASPNETCORE_ENVIRONMENT
              value: Development
            - name: DOTNET_RUNNING_IN_CONTAINER
              value: "true"
            - name: EmailSettings__Email
              value: paulomvbumba@gmail.com
            - name: EmailSettings__Host
              value: smtp.gmail.com
            - name: EmailSettings__Password
              value: '********'
            - name: EmailSettings__Port
              value: "587"
            - name: RabbitMQ__Host
              value: rabbitmq
            - name: RabbitMQ__Port
              value: "5672"
          image: notification-service
          name: notification-service
      restartPolicy: Always
