apiVersion: v1
data:
  prometheus.yml: |
    global:
      scrape_interval: 15s       # A cada 15 segundos ele vai coletar as métricas

    scrape_configs:
      - job_name: 'prometheus'  # Monitorando o próprio Prometheus
        static_configs:
          - targets: ['localhost:9090']

      # Exemplo de monitoramento RabbitMQ (se tiver o exporter rodando)
      - job_name: 'rabbitmq'
        static_configs:
          - targets: ['rabbitmq:15672']

      # Exemplo para monitorar sua API (se ela expuser métricas Prometheus)
      - job_name: 'notification-service'
        static_configs:
          - targets: ['notification-service:7296']
kind: ConfigMap
metadata:
  annotations:
    use-subpath: "true"
  labels:
    io.kompose.service: prometheus
  name: prometheus-cm0
