apiVersion: v1
kind: Service
metadata:
  annotations:
    kompose.cmd: C:\Users\Paulo_Bumba\AppData\Local\Microsoft\WinGet\Links\kompose.exe convert -f docker-compose.yml
    kompose.version: 1.37.0 (fb0539e64)
  labels:
    io.kompose.service: sqlserver
  name: sqlserver
spec:
  type: LoadBalancer        # <-- ADICIONADO
  ports:
    - name: "1433"
      port: 1433
      targetPort: 1433
  selector:
    io.kompose.service: sqlserver
