global:
  scrape_interval: 15s

scrape_configs:
  - job_name: 'notification-service'
    metrics_path: /metrics
    static_configs:
      - targets: ['notification-service:7296']

  - job_name: 'rabbitmq'
    metrics_path: /metrics
    static_configs:
      - targets: ['rabbitmq-exporter:9419']
  - job_name: 'redis'
    metrics_path: /metrics  
